07-Jun-23 15:35:16 - INFO - /home/leonel/serverpulse/servers_monitor/views.py changed, reloading.
07-Jun-23 15:41:06 - INFO - /home/leonel/serverpulse/serverPulse/settings.py changed, reloading.
07-Jun-23 15:45:15 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:45:15 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:45:15 - WARNING - Not Found: /static/js/request_token_sys_admin.js
07-Jun-23 15:45:15 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:45:15 - WARNING - Not Found: /favicon.ico
07-Jun-23 15:45:26 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:45:26 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:45:26 - WARNING - Not Found: /static/js/request_token_sys_admin.js
07-Jun-23 15:45:27 - INFO - Singin: Se hace petición por el método: GET
07-Jun-23 15:45:28 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:45:34 - INFO - Singin: Se hace petición por el método: POST
07-Jun-23 15:45:34 - ERROR - Singin: Los datos que ingreso el usuario no son correctos
07-Jun-23 15:45:34 - INFO - Singin: Se hace petición por el método: GET
07-Jun-23 15:45:34 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:45:41 - INFO - Singin: Se hace petición por el método: POST
07-Jun-23 15:45:41 - ERROR - Singin: Los datos que ingreso el usuario no son correctos
07-Jun-23 15:45:41 - INFO - Singin: Se hace petición por el método: GET
07-Jun-23 15:45:41 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:46:30 - INFO - Singin: Se hace petición por el método: POST
07-Jun-23 15:46:30 - ERROR - Singin: Los datos que ingreso el usuario no son correctos
07-Jun-23 15:46:30 - INFO - Singin: Se hace petición por el método: GET
07-Jun-23 15:46:30 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:46:32 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:46:32 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:46:32 - WARNING - Not Found: /static/js/request_token_sys_admin.js
07-Jun-23 15:46:35 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:46:35 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:46:35 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:46:35 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:46:35 - WARNING - Not Found: /static/js/request_token_sys_admin.js
07-Jun-23 15:46:46 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:46:46 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:46:46 - WARNING - Not Found: /static/js/request_token_sys_admin.js
07-Jun-23 15:46:52 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:46:52 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:46:52 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:46:52 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:46:52 - WARNING - Not Found: /static/js/request_token_sys_admin.js
07-Jun-23 15:46:55 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:46:55 - WARNING - Not Found: /static/styles/styles.css
07-Jun-23 15:46:55 - WARNING - Not Found: /static/js/request_token_sys_admin.js
07-Jun-23 15:47:03 - WARNING - Not Found: /serverpulse/
07-Jun-23 15:47:26 - INFO - /home/leonel/serverpulse/serverPulse/settings.py changed, reloading.
07-Jun-23 15:47:29 - WARNING - Not Found: /serverpulse/
07-Jun-23 15:47:45 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:47:53 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:47:53 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:47:53 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:47:56 - INFO - solicitar_token Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:47:56 - ERROR - solicitar_token Sys Admin: usuario no encontrado
07-Jun-23 15:48:06 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:48:10 - INFO - Singin: Se hace petición por el método: GET
07-Jun-23 15:48:13 - INFO - Singin: Se hace petición por el método: POST
07-Jun-23 15:48:13 - ERROR - Singin: Los datos que ingreso el usuario no son correctos
07-Jun-23 15:48:13 - INFO - Singin: Se hace petición por el método: GET
07-Jun-23 15:50:08 - INFO - Singin: Se hace petición por el método: GET
07-Jun-23 15:50:42 - INFO - Singin: Se hace petición por el método: POST
07-Jun-23 15:50:42 - ERROR - Singin: Los datos que ingreso el usuario no son correctos
07-Jun-23 15:50:42 - INFO - Singin: Se hace petición por el método: GET
07-Jun-23 15:51:50 - INFO - Singin: Se hace petición por el método: POST
07-Jun-23 15:51:50 - ERROR - Internal Server Error: /serverpulse/singin/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonel/serverpulse/auth_app/views.py", line 53, in singin
    Sysadmin.password = validar_password(password)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonel/serverpulse/auth_app/views.py", line 102, in validar_password
    return check_password(password)
           ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: check_password() missing 1 required positional argument: 'encoded'
07-Jun-23 15:53:12 - INFO - /home/leonel/serverpulse/auth_app/views.py changed, reloading.
07-Jun-23 15:53:22 - INFO - Singin: Se hace petición por el método: GET
07-Jun-23 15:53:23 - INFO - Singin: Se hace petición por el método: GET
07-Jun-23 15:53:33 - INFO - Singin: Se hace petición por el método: POST
07-Jun-23 15:53:33 - INFO - Singin: El usuario ingreso adecuadamente en su sesión
07-Jun-23 15:53:33 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:53:49 - INFO - solicitar_token Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:53:49 - ERROR - solicitar_token Sys Admmin: el token no registro adecuadamente
07-Jun-23 15:54:23 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:54:23 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:54:23 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:54:45 - INFO - solicitar_token Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:54:45 - ERROR - solicitar_token Sys Admmin: el token no registro adecuadamente
07-Jun-23 15:55:03 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:03 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:03 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:26 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:26 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:26 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:28 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:28 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:28 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:37 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:37 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:38 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:39 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:39 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:39 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:40 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:40 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:40 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:40 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:40 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:40 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:41 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:41 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:41 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:41 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:41 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:41 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:42 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:42 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:42 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:42 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:42 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:42 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:43 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:43 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:43 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:55:43 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:55:43 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:55:43 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:56:02 - INFO - login Sys Admin: Se hace petición por el método: POST
07-Jun-23 15:56:02 - ERROR - login Sys Admin: Error datos inválidos por parte del usuario
07-Jun-23 15:56:02 - INFO - login Sys Admin: Se hace petición por el método: GET
07-Jun-23 15:57:10 - ERROR - Internal Server Error: /admin/auth_app/admonglobal/add/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: el valor nulo en la columna «is_authorize» de la relación «auth_app_admonglobal» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (Leonel Macedo, macedo238, null, null, asdfdsf, 0, null, 2023-06-07 21:53:13-06, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/lib/python3/dist-packages/django/contrib/admin/options.py", line 1099, in save_model
    obj.save()
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/lib/python3/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: el valor nulo en la columna «is_authorize» de la relación «auth_app_admonglobal» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (Leonel Macedo, macedo238, null, null, asdfdsf, 0, null, 2023-06-07 21:53:13-06, null, null).

07-Jun-23 15:57:25 - ERROR - Internal Server Error: /admin/auth_app/admonglobal/add/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: el valor nulo en la columna «is_authorize» de la relación «auth_app_admonglobal» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (Leonel Macedo, macedo238, null, null, asdfdsf, 0, null, 2023-06-07 21:53:13-06, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/lib/python3/dist-packages/django/contrib/admin/options.py", line 1099, in save_model
    obj.save()
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/lib/python3/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: el valor nulo en la columna «is_authorize» de la relación «auth_app_admonglobal» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (Leonel Macedo, macedo238, null, null, asdfdsf, 0, null, 2023-06-07 21:53:13-06, null, null).

07-Jun-23 15:58:54 - INFO - /home/leonel/serverpulse/serverPulse/settings.py changed, reloading.
